# K리그 데이터포탈 데이터 전처리

In [1]:
from glob import glob

import pandas as pd

#최종 df 먼저 생성 
df = []
years = [2021,2022,2023]

for year in years:
    datas = glob(f'k_datasets/{year}/*.xlsx')
    print(datas)

    teams = [xlsx.split('_')[-2] for xlsx in datas]

    # concat 기준이 될 df 먼저 생성, 
    df_year = pd.read_excel(f'{datas[0]}', engine='openpyxl')

    # H/A 헷갈려서 기준 잡는 열 생성 / 시즌 열 생성
    df_year['기준'] = teams[0]
    df_year['시즌'] = year

    # 새로운 df 불러오고 기준 df에 concat하기
    for xlsx in datas[1:]:
        team_name = xlsx.split('_')[-2]
        df_temp = pd.read_excel(f'{xlsx}', engine="openpyxl")
        df_temp["기준"] = f'{team_name}'
        df_temp["시즌"] = year
        df_year = pd.concat([df_year, df_temp])
    print(df_year.shape)
    df.append(df_year)

df = pd.concat(df, ignore_index=True)
print(df.shape)
df.tail()

['k_datasets/2021\\2021_daegu_data.xlsx', 'k_datasets/2021\\2021_gangwon_data.xlsx', 'k_datasets/2021\\2021_gwangju_data.xlsx', 'k_datasets/2021\\2021_incheon_data.xlsx', 'k_datasets/2021\\2021_jeju_data.xlsx', 'k_datasets/2021\\2021_jeonbuk_data.xlsx', 'k_datasets/2021\\2021_pohang_data.xlsx', 'k_datasets/2021\\2021_seongnam_data.xlsx', 'k_datasets/2021\\2021_seoul_data.xlsx', 'k_datasets/2021\\2021_suwonFC_data.xlsx', 'k_datasets/2021\\2021_suwon_data.xlsx', 'k_datasets/2021\\2021_ulsan_data.xlsx']
(456, 78)
['k_datasets/2022\\2022_daegu_data.xlsx', 'k_datasets/2022\\2022_gangwon_data.xlsx', 'k_datasets/2022\\2022_gimcheon_data.xlsx', 'k_datasets/2022\\2022_incheon_data.xlsx', 'k_datasets/2022\\2022_jeju_data.xlsx', 'k_datasets/2022\\2022_jeonbuk_data.xlsx', 'k_datasets/2022\\2022_pohang_data.xlsx', 'k_datasets/2022\\2022_seongnam_data.xlsx', 'k_datasets/2022\\2022_seoul_data.xlsx', 'k_datasets/2022\\2022_suwonFC_data.xlsx', 'k_datasets/2022\\2022_suwon_data.xlsx', 'k_datasets/2022\\2022_ulsan_data.xlsx']
(456, 78)
['k_datasets/2023\\2023_daegu_data.xlsx', 'k_datasets/2023\\2023_daejeon_data.xlsx', 'k_datasets/2023\\2023_gangwon_data.xlsx', 'k_datasets/2023\\2023_gwangju_data.xlsx', 'k_datasets/2023\\2023_incheon_data.xlsx', 'k_datasets/2023\\2023_jeju_data.xlsx', 'k_datasets/2023\\2023_jeonbuk_data.xlsx', 'k_datasets/2023\\2023_pohang_data.xlsx', 'k_datasets/2023\\2023_seoul_data.xlsx', 'k_datasets/2023\\2023_suwonFC_data.xlsx', 'k_datasets/2023\\2023_suwon_data.xlsx', 'k_datasets/2023\\2023_ulsan_data.xlsx']
(420, 78)
(1332, 78)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-69,LABEL-70,LABEL-71,LABEL-72,LABEL-73,LABEL-74,LABEL-75,LABEL-76,기준,시즌
1327,31,수원FCvs울산,AWAY,3,3,9,8,0,1,6,...,20,47,17,11,10,9,1,0,ulsan,2023
1328,32,포항vs울산,AWAY,0,0,4,1,0,3,2,...,29,52,20,5,11,11,5,0,ulsan,2023
1329,33,울산vs인천,HOME,0,0,9,2,1,6,5,...,12,42,16,7,7,2,2,0,ulsan,2023
1330,34,광주vs울산,AWAY,0,0,17,5,6,6,6,...,18,58,11,11,16,6,1,0,ulsan,2023
1331,35,울산vs대구,HOME,2,2,12,5,2,5,5,...,24,59,11,7,8,7,1,0,ulsan,2023

In [2]:
# K_Columns 에서 컬럼명 가져오기
names = pd.read_excel('k_datasets\K_columns.xlsx', engine="openpyxl")
print(names.shape)
names.head()

(2, 48)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-39,LABEL-40,LABEL-41,LABEL-42,LABEL-43,LABEL-44,LABEL-45,LABEL-46,LABEL-47,LABEL-48
0,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,블락,볼미스,파울,피파울,경고,퇴장,NaN,NaN,NaN,NaN
1,시도,성공,성공%,시도,성공,성공%,시도,성공,성공%,시도,...,성공%,시도,성공,성공%,시도,성공,성공%,시도,성공,성공%

In [3]:
# 필요없는 열 제거 (성공%만 가져옴)
temp = names.drop(columns=['LABEL-45','LABEL-46','LABEL-47','LABEL-48']) 

# 컬럼명 가져와서 리스트로 저장
rows = temp.iloc[0].to_list()
print(len(rows))
print(rows)

44
['Rnd.', '대회', 'H/A', '득점', '도움', '슈팅', '유효 슈팅', '블락된슈팅', '벗어난슈팅', 'PA내 슈팅', 'PA외 슈팅', '프리킥 슈팅', '프리킥 유효슈팅', '프리킥 크로스', '오프사이드', '코너킥', '스로인', '드리블', '패스', '키패스', '전방패스', '후방패스', '횡패스', '공격진영 패스', '수비진영 패스', '중앙진영 패스', '롱패스', '중거리패스', '단거리패스', '크로스', '탈압박', '경합 지상', '경합 공중', '태클', '클리어링', '인터셉트', '차단', '획득', '블락', '볼미스', '파울', '피파울', '경고', '퇴장']

In [4]:
# df의 컬럼 개수를 K_columns에 맞춰 개수 맞추기
drop_columns = ['14', '15','20','21','23','24','27', '28' ,'30' ,'31' ,'33' ,'34', '36', '37', '39', '40','42', '43' ,'45',
               '46' ,'48', '49' ,'51' ,'52' ,'54', '55', '58', '59', '61', '62', '64', '65']
for idx in (drop_columns):
    df = df.drop(columns=[f'LABEL-{idx}'])

# 확인
print(df.shape)
# print(df.columns)
df.head()

(1332, 46)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-69,LABEL-70,LABEL-71,LABEL-72,LABEL-73,LABEL-74,LABEL-75,LABEL-76,기준,시즌
0,1,대구vs수원FC,HOME,1,1,13,4,2,7,5,...,48,87,3,9,13,14,1,0,daegu,2021
1,2,인천vs대구,AWAY,1,0,14,2,5,7,7,...,59,102,2,10,13,22,1,0,daegu,2021
2,3,대구vs광주,HOME,1,0,17,4,6,7,10,...,42,96,2,12,18,14,2,0,daegu,2021
3,4,대구vs제주,HOME,1,0,16,4,3,9,10,...,42,102,2,14,13,14,2,0,daegu,2021
4,5,전북vs대구,AWAY,2,2,17,4,10,3,10,...,50,102,3,5,13,15,4,1,daegu,2021

In [5]:
# 컬럼명 변경 ("기준"열 제외한)
for idx, column in enumerate(df.columns[:-2]):
    df = df.rename(columns={f"{column}": f"{rows[idx]}"})

# 컬럼명 변경 확인
df.head(1)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,차단,획득,블락,볼미스,파울,피파울,경고,퇴장,기준,시즌
0,1,대구vs수원FC,HOME,1,1,13,4,2,7,5,...,48,87,3,9,13,14,1,0,daegu,2021

In [6]:
# 대회별 득점 비교 후 경기결과 열에 저장
for i in df["대회"].value_counts().index.tolist():
    for j in range(1,39): # 총 35개 라운드 수집
        H_score = df[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME")]["득점"]
        A_score = df[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY")]["득점"]
        if len(H_score) > 0:
            if H_score.iloc[0] > A_score.iloc[0]:
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'W'
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY"), "경기결과"] = 'L'
            elif H_score.iloc[0] < A_score.iloc[0]:
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'L'
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY"), "경기결과"] = 'W'
            else:
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'D'
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY"), "경기결과"] = 'D'

In [7]:
# 보기좋게 라운드 순으로 정렬
df = df.sort_values('Rnd.')

# 1,2라운드 승패 확인
df.head(24)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,획득,블락,볼미스,파울,피파울,경고,퇴장,기준,시즌,경기결과
0,1,대구vs수원FC,HOME,1,1,13,4,2,7,5,...,87,3,9,13,14,1,0,daegu,2021,D
456,1,대구vs서울,HOME,0,0,10,1,3,6,7,...,53,23,6,17,11,4,0,daegu,2022,L
608,1,제주vs포항,HOME,0,0,9,1,3,5,5,...,59,23,9,16,16,2,0,jeju,2022,L
1192,1,서울vs인천,HOME,2,1,13,7,2,4,7,...,41,31,5,16,12,3,0,seoul,2023,W
912,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,51,19,4,16,9,3,0,daegu,2023,L
494,1,강원vs성남,HOME,2,1,11,4,1,6,7,...,58,27,8,12,12,1,0,gangwon,2022,W
38,1,울산vs강원,AWAY,0,0,8,2,5,1,3,...,67,3,5,12,15,1,1,gangwon,2021,L
152,1,성남vs제주,AWAY,0,0,11,2,6,3,5,...,117,1,5,15,10,0,1,jeju,2021,D
874,1,울산vs김천,HOME,0,0,22,3,6,13,14,...,78,26,7,11,13,2,0,ulsan,2022,D
532,1,울산vs김천,AWAY,0,0,6,1,1,4,4,...,48,35,5,13,11,2,0,gimcheon,2022,D
1227,1,제주vs수원FC,AWAY,0,0,9,2,2,5,7,...,55,19,7,11,15,3,0,suwonFC,2023,D
114,1,포항vs인천,AWAY,1,1,4,1,1,2,0,...,73,6,4,13,15,3,0,incheon,2021,L
646,1,전북vs수원FC,HOME,1,1,9,3,2,4,4,...,57,27,6,22,11,4,0,jeonbuk,2022,W
760,1,대구vs서울,AWAY,2,2,11,3,1,7,6,...,57,24,3,11,16,2,0,seoul,2022,W
836,1,인천vs수원,AWAY,0,0,7,1,3,3,4,...,55,24,6,9,15,2,1,suwon,2022,L
570,1,인천vs수원,HOME,1,1,17,6,4,7,8,...,59,30,7,15,9,1,0,incheon,2022,W
1262,1,수원vs광주,HOME,0,0,10,5,4,1,7,...,67,16,3,13,12,2,0,suwon,2023,W
1297,1,울산vs전북,HOME,2,0,10,4,4,2,7,...,63,17,5,11,16,2,0,ulsan,2023,W
76,1,수원vs광주,AWAY,0,0,2,1,0,1,1,...,77,4,3,14,16,3,0,gwangju,2021,L
798,1,전북vs수원FC,AWAY,0,0,9,1,3,5,5,...,70,23,4,11,22,2,0,suwonFC,2022,L
947,1,대전vs강원,HOME,2,1,9,4,1,4,5,...,71,20,8,13,7,5,0,daejeon,2023,W
1157,1,포항vs대구,HOME,3,3,12,5,2,5,7,...,52,19,6,9,14,1,0,pohang,2023,W
190,1,전북vs서울,HOME,2,1,9,4,1,4,5,...,108,5,6,10,5,0,0,jeonbuk,2021,W
1017,1,수원vs광주,AWAY,1,1,12,3,3,6,7,...,73,33,8,12,13,2,0,gwangju,2023,L

In [8]:
# 마지막 라운드 승패 확인
df.tail(12)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,획득,블락,볼미스,파울,피파울,경고,퇴장,기준,시즌,경기결과
683,38,전북vs인천,HOME,2,0,19,5,6,8,13,...,52,23,11,8,10,1,0,jeonbuk,2022,W
797,38,수원FCvs서울,AWAY,2,1,9,6,1,2,8,...,48,28,10,13,8,2,0,seoul,2022,W
75,38,강원vs성남,HOME,2,0,11,7,3,1,8,...,68,1,5,14,14,3,0,gangwon,2021,W
417,38,수원FCvs수원,AWAY,0,0,14,6,4,4,12,...,87,4,7,8,13,0,0,suwon,2021,L
911,38,울산vs제주,HOME,1,1,9,3,2,4,6,...,50,24,1,5,6,1,0,ulsan,2022,L
493,38,성남vs대구,AWAY,4,3,6,5,1,0,4,...,49,31,8,11,14,0,0,daegu,2022,D
873,38,김천vs수원,AWAY,3,2,11,7,1,3,8,...,53,21,6,9,17,1,0,suwon,2022,W
531,38,포항vs강원,AWAY,0,0,11,0,2,9,6,...,53,19,5,10,9,3,0,gangwon,2022,L
835,38,수원FCvs서울,HOME,0,0,10,0,5,5,5,...,52,19,6,9,13,0,0,suwonFC,2022,L
37,38,울산vs대구,AWAY,0,0,9,4,1,4,3,...,84,9,12,13,10,3,0,daegu,2021,L
379,38,수원FCvs수원,HOME,2,1,12,3,4,5,5,...,81,4,8,12,8,2,0,suwonFC,2021,W
455,38,울산vs대구,HOME,2,2,19,6,9,4,10,...,99,1,4,10,12,1,0,ulsan,2021,W

# 트랜스퍼마켓 데이터 전처리

In [14]:
# transfer markt 데이터 불러오고 불필요 열 제거
tm_data_2021 = pd.read_excel('k_datasets/K_trsfmk_2021.xlsx', engine='openpyxl').drop(columns=['LABEL-1','LABEL-2','LABEL-4','LABEL-5'])
tm_data_2022 = pd.read_excel('k_datasets/K_trsfmk_2022.xlsx', engine='openpyxl').drop(columns=['LABEL-1','LABEL-2','LABEL-4'])
tm_data_2023 = pd.read_excel('k_datasets/K_trsfmk_2023.xlsx', engine='openpyxl').drop(columns=['LABEL-1','LABEL-2','LABEL-4'])

# 열 이름 변경
tm_data_2021 = tm_data_2021.rename(columns={'LABEL-3' : '구단', 'LABEL-6' : '소속 선수 수',
                                'LABEL-7' : '평균 나이','LABEL-8' : '용병 수',
                                'LABEL-9' : '평균 가치', 'LABEL-10' : '총 가치'})

tm_data_2022 = tm_data_2022.rename(columns={'LABEL-3' : '구단', 'LABEL-5' : '소속 선수 수',
                                'LABEL-6' : '평균 나이','LABEL-7' : '용병 수',
                                'LABEL-8' : '평균 가치', 'LABEL-9' : '총 가치'})

tm_data_2023 = tm_data_2023.rename(columns={'LABEL-3' : '구단', 'LABEL-5' : '소속 선수 수',
                                'LABEL-6' : '평균 나이','LABEL-7' : '용병 수',
                                'LABEL-8' : '평균 가치', 'LABEL-9' : '총 가치'})

# 구단 이름 수정
tm_data_2021['구단'] = ['jeonbuk', 'ulsan', 'seoul', 'suwon', 'incheon', 'suwonFC',
                           'gangwon', 'jeju', 'pohang', 'seongnam','daegu','gwangju']

tm_data_2022['구단'] = ['jeonbuk', 'seoul', 'gimcheon', 'ulsan', 'suwon', 'jeju',
                           'pohang', 'incheon', 'gangwon', 'seongnam','daegu','suwonFC']

tm_data_2023['구단'] = ['jeonbuk', 'ulsan', 'seoul', 'suwon', 'daejeon', 'gangwon',
                           'jeju', 'incheon', 'gwangju', 'pohang','daegu','suwonFC']

In [15]:
# 평균 가치, 총 가치 열에서 €, k, m 제거

tm_data_2021['평균 가치'] = tm_data_2021['평균 가치'].str.replace('€', '').str.replace('k', '').astype(float)
tm_data_2021['총 가치'] = tm_data_2021['총 가치'].str.replace('€', '').str.replace('m', '').astype(float)

tm_data_2022['평균 가치'] = tm_data_2022['평균 가치'].str.replace('€', '').str.replace('k', '').astype(float)
tm_data_2022['총 가치'] = tm_data_2022['총 가치'].str.replace('€', '').str.replace('m', '').astype(float)

tm_data_2023['평균 가치'] = tm_data_2023['평균 가치'].str.replace('€', '').str.replace('k', '').astype(float)
tm_data_2023['총 가치'] = tm_data_2023['총 가치'].str.replace('€', '').str.replace('m', '').astype(float)

In [19]:
display(tm_data_2021)
display(tm_data_2022)
display(tm_data_2023)

          구단  소속 선수 수  평균 나이  용병 수  평균 가치   총 가치
0    jeonbuk       36   25.0     5  600.0  21.60
1      ulsan       34   25.9     4  598.0  20.33
2      seoul       40   23.0     4  441.0  17.63
3      suwon       40   23.9     4  376.0  15.05
4    incheon       42   24.8     4  304.0  12.75
5    suwonFC       36   25.6     5  350.0  12.60
6    gangwon       41   23.3     5  307.0  12.58
7       jeju       38   24.3     3  317.0  12.05
8     pohang       49   23.1     5  240.0  11.78
9   seongnam       35   25.1     4  336.0  11.75
10     daegu       42   22.9     5  279.0  11.70
11   gwangju       37   25.6     4  288.0  10.65

          구단  소속 선수 수  평균 나이  용병 수  평균 가치   총 가치
0    jeonbuk       52   23.4     4  426.0  22.18
1      seoul       49   23.2     6  374.0  18.35
2   gimcheon       40   23.5     0  439.0  17.58
3      ulsan       34   26.3     5  502.0  17.08
4      suwon       42   24.7     5  322.0  13.53
5       jeju       37   24.2     2  328.0  12.13
6     pohang       40   24.3     4  296.0  11.85
7    incheon       37   25.9     4  300.0  11.10
8    gangwon       33   24.2     6  326.0  10.75
9   seongnam       40   24.8     3  247.0   9.88
10     daegu       43   22.6     6  228.0   9.83
11   suwonFC       32   26.3     4  287.0   9.18

         구단  소속 선수 수  평균 나이  용병 수  평균 가치   총 가치
0   jeonbuk       47   25.2     6  415.0  19.50
1     ulsan       30   28.8     5  632.0  18.95
2     seoul       42   25.4     6  358.0  15.05
3     suwon       47   26.0     7  314.0  14.78
4   daejeon       45   24.5     5  285.0  12.83
5   gangwon       45   24.6     6  274.0  12.33
6      jeju       31   27.5     3  384.0  11.90
7   incheon       35   26.3     5  315.0  11.03
8   gwangju       33   26.3     5  329.0  10.85
9    pohang       37   25.6     4  281.0  10.40
10    daegu       41   24.2     5  254.0  10.40
11  suwonFC       37   27.1     4  277.0  10.25

In [20]:
# df에 tm_data_2023 합치기
tm_columns = tm_data_2021.columns[1:]

# df에 열 먼저 생성
for column in tm_columns:
    df[f'{column}'] = None
df.head(1)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,경고,퇴장,기준,시즌,경기결과,소속 선수 수,평균 나이,용병 수,평균 가치,총 가치
0,1,대구vs수원FC,HOME,1,1,13,4,2,7,5,...,1,0,daegu,2021,D,None,None,None,None,None

In [21]:
# !TODO
# 구단/시즌 별 트랜스퍼마켓 데이터 합치기

# 2021
for column in tm_data_2021.columns[1:]:
    for i in df['기준']:
        for j in tm_data_2021['구단']:
            if i == j:
                df.loc[(df['기준'] == i) &(df['시즌'] == 2021), f'{column}'] = tm_data_2021.loc[tm_data_2021['구단'] == j , f'{column}'].values[0]
print('2021 end !')

#2022
for column in tm_data_2022.columns[1:]:
    for i in df['기준']:
        for j in tm_data_2022['구단']:
            if i == j:
                df.loc[(df['기준'] == i) &(df['시즌'] == 2022), f'{column}'] = tm_data_2022.loc[tm_data_2022['구단'] == j , f'{column}'].values[0]
print('2022 end !')

#2023
for column in tm_data_2023.columns[1:]:
    for i in df['기준']:
        for j in tm_data_2023['구단']:
            if i == j:
                df.loc[(df['기준'] == i) &(df['시즌'] == 2023), f'{column}'] = tm_data_2023.loc[tm_data_2023['구단'] == j , f'{column}'].values[0]
print('2023 end !')

# df의 맨앞, 맨뒤 2개의 라운드 확인
df.head(24)

2021 end !
2022 end !
2023 end !

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,경고,퇴장,기준,시즌,경기결과,소속 선수 수,평균 나이,용병 수,평균 가치,총 가치
0,1,대구vs수원FC,HOME,1,1,13,4,2,7,5,...,1,0,daegu,2021,D,42,22.9,5,279.0,11.7
456,1,대구vs서울,HOME,0,0,10,1,3,6,7,...,4,0,daegu,2022,L,43,22.6,6,228.0,9.83
608,1,제주vs포항,HOME,0,0,9,1,3,5,5,...,2,0,jeju,2022,L,37,24.2,2,328.0,12.13
1192,1,서울vs인천,HOME,2,1,13,7,2,4,7,...,3,0,seoul,2023,W,42,25.4,6,358.0,15.05
912,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,3,0,daegu,2023,L,41,24.2,5,254.0,10.4
494,1,강원vs성남,HOME,2,1,11,4,1,6,7,...,1,0,gangwon,2022,W,33,24.2,6,326.0,10.75
38,1,울산vs강원,AWAY,0,0,8,2,5,1,3,...,1,1,gangwon,2021,L,41,23.3,5,307.0,12.58
152,1,성남vs제주,AWAY,0,0,11,2,6,3,5,...,0,1,jeju,2021,D,38,24.3,3,317.0,12.05
874,1,울산vs김천,HOME,0,0,22,3,6,13,14,...,2,0,ulsan,2022,D,34,26.3,5,502.0,17.08
532,1,울산vs김천,AWAY,0,0,6,1,1,4,4,...,2,0,gimcheon,2022,D,40,23.5,0,439.0,17.58
1227,1,제주vs수원FC,AWAY,0,0,9,2,2,5,7,...,3,0,suwonFC,2023,D,37,27.1,4,277.0,10.25
114,1,포항vs인천,AWAY,1,1,4,1,1,2,0,...,3,0,incheon,2021,L,42,24.8,4,304.0,12.75
646,1,전북vs수원FC,HOME,1,1,9,3,2,4,4,...,4,0,jeonbuk,2022,W,52,23.4,4,426.0,22.18
760,1,대구vs서울,AWAY,2,2,11,3,1,7,6,...,2,0,seoul,2022,W,49,23.2,6,374.0,18.35
836,1,인천vs수원,AWAY,0,0,7,1,3,3,4,...,2,1,suwon,2022,L,42,24.7,5,322.0,13.53
570,1,인천vs수원,HOME,1,1,17,6,4,7,8,...,1,0,incheon,2022,W,37,25.9,4,300.0,11.1
1262,1,수원vs광주,HOME,0,0,10,5,4,1,7,...,2,0,suwon,2023,W,47,26.0,7,314.0,14.78
1297,1,울산vs전북,HOME,2,0,10,4,4,2,7,...,2,0,ulsan,2023,W,30,28.8,5,632.0,18.95
76,1,수원vs광주,AWAY,0,0,2,1,0,1,1,...,3,0,gwangju,2021,L,37,25.6,4,288.0,10.65
798,1,전북vs수원FC,AWAY,0,0,9,1,3,5,5,...,2,0,suwonFC,2022,L,32,26.3,4,287.0,9.18
947,1,대전vs강원,HOME,2,1,9,4,1,4,5,...,5,0,daejeon,2023,W,45,24.5,5,285.0,12.83
1157,1,포항vs대구,HOME,3,3,12,5,2,5,7,...,1,0,pohang,2023,W,37,25.6,4,281.0,10.4
190,1,전북vs서울,HOME,2,1,9,4,1,4,5,...,0,0,jeonbuk,2021,W,36,25.0,5,600.0,21.6
1017,1,수원vs광주,AWAY,1,1,12,3,3,6,7,...,2,0,gwangju,2023,L,33,26.3,5,329.0,10.85

In [22]:
df.to_csv('K-League-data.csv')

# 기술통계

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1332 entries, 0 to 455
Data columns (total 52 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rnd.      1332 non-null   int64
 1   대회        1332 non-null   object
 2   H/A       1332 non-null   object
 3   득점        1332 non-null   int64
 4   도움        1332 non-null   int64
 5   슈팅        1332 non-null   int64
 6   유효 슈팅     1332 non-null   int64
 7   블락된슈팅     1332 non-null   int64
 8   벗어난슈팅     1332 non-null   int64
 9   PA내 슈팅    1332 non-null   int64
 10  PA외 슈팅    1332 non-null   int64
 11  프리킥 슈팅    1332 non-null   int64
 12  프리킥 유효슈팅  1332 non-null   int64
 13  프리킥 크로스   1332 non-null   float64
 14  오프사이드     1332 non-null   int64
 15  코너킥       1332 non-null   int64
 16  스로인       1332 non-null   int64
 17  드리블       1332 non-null   float64
 18  패스        1332 non-null   float64
 19  키패스       1332 non-null   int64
 20  전방패스      1332 non-null   float64
 21  후방패스      1332 non-null   float64
 22  횡패스       1332 non-null   float64
 23  공격진영 패스   1332 non-null   float64
 24  수비진영 패스   1332 non-null   float64
 25  중앙진영 패스   1332 non-null   float64
 26  롱패스       1332 non-null   float64
 27  중거리패스     1332 non-null   float64
 28  단거리패스     1332 non-null   float64
 29  크로스       1332 non-null   float64
 30  탈압박       1332 non-null   int64
 31  경합 지상     1332 non-null   float64
 32  경합 공중     1332 non-null   float64
 33  태클        1332 non-null   float64
 34  클리어링      1332 non-null   int64
 35  인터셉트      1332 non-null   int64
 36  차단        1332 non-null   int64
 37  획득        1332 non-null   int64
 38  블락        1332 non-null   int64
 39  볼미스       1332 non-null   int64
 40  파울        1332 non-null   int64
 41  피파울       1332 non-null   int64
 42  경고        1332 non-null   int64
 43  퇴장        1332 non-null   int64
 44  기준        1332 non-null   object
 45  시즌        1332 non-null   int64
 46  경기결과      1332 non-null   object
 47  소속 선수 수   1332 non-null   object
 48  평균 나이     1332 non-null   object
 49  용병 수      1332 non-null   object
 50  평균 가치     1332 non-null   object
 51  총 가치      1332 non-null   object
dtypes: float64(16), int64(27), object(9)
memory usage: 551.5+ KB

In [ ]:
df.isnull().sum()

Rnd.        0
대회          0
H/A         0
득점          0
도움          0
슈팅          0
유효 슈팅       0
블락된슈팅       0
벗어난슈팅       0
PA내 슈팅      0
PA외 슈팅      0
프리킥 슈팅      0
프리킥 유효슈팅    0
프리킥 크로스     0
오프사이드       0
코너킥         0
스로인         0
드리블         0
패스          0
키패스         0
전방패스        0
후방패스        0
횡패스         0
공격진영 패스     0
수비진영 패스     0
중앙진영 패스     0
롱패스         0
중거리패스       0
단거리패스       0
크로스         0
탈압박         0
경합 지상       0
경합 공중       0
태클          0
클리어링        0
인터셉트        0
차단          0
획득          0
블락          0
볼미스         0
파울          0
피파울         0
경고          0
퇴장          0
기준          0
시즌          0
경기결과        0
소속 선수 수     0
평균 나이       0
용병 수        0
평균 가치       0
총 가치        0
dtype: int64

In [ ]:
# 열이 많아서 슬라이싱 - 1

df[['Rnd.', '대회', 'H/A', '득점', '도움', '슈팅', '유효 슈팅', '블락된슈팅', '벗어난슈팅',
       'PA내 슈팅', 'PA외 슈팅', '프리킥 슈팅', '프리킥 유효슈팅', '프리킥 크로스','오프사이드']].describe()

,Rnd.,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,PA외 슈팅,프리킥 슈팅,프리킥 유효슈팅,프리킥 크로스,오프사이드
count,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000
mean,19.027027,1.263514,0.795796,11.460961,4.007508,2.478979,4.974474,6.593844,4.867117,0.431682,0.139640,19.920195,1.408408
std,10.726958,1.098632,0.897637,4.053268,2.174562,1.823631,2.367310,2.982452,2.455231,0.652558,0.377849,32.584450,1.324742
min,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,0.000000,0.000000,9.000000,2.000000,1.000000,3.000000,4.000000,3.000000,0.000000,0.000000,0.000000,0.000000
50%,19.000000,1.000000,1.000000,11.000000,4.000000,2.000000,5.000000,6.000000,5.000000,0.000000,0.000000,0.000000,1.000000
75%,28.000000,2.000000,1.000000,14.000000,5.000000,3.000000,6.000000,8.000000,6.000000,1.000000,0.000000,42.500000,2.000000
max,38.000000,7.000000,5.000000,27.000000,13.000000,11.000000,15.000000,20.000000,16.000000,4.000000,2.000000,100.000000,10.000000

In [ ]:
# 열이 많아서 슬라이싱 - 2

df[['코너킥','스로인', '드리블', '패스', '키패스', '전방패스', '후방패스', '횡패스', '공격진영 패스', '수비진영 패스',
       '중앙진영 패스', '롱패스', '중거리패스', '단거리패스', '크로스', '탈압박']].describe()

,코너킥,스로인,드리블,패스,키패스,전방패스,후방패스,횡패스,공격진영 패스,수비진영 패스,중앙진영 패스,롱패스,중거리패스,단거리패스,크로스,탈압박
count,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000
mean,4.290541,19.987237,36.894444,81.009685,6.752252,66.447973,95.989865,89.623724,75.637312,77.731532,84.567718,56.392342,85.203679,85.058934,22.128378,2.578078
std,2.396241,5.900807,24.104584,6.474343,2.961339,8.372458,2.569367,5.567650,8.765133,9.650162,5.999876,12.315111,6.340819,5.190515,10.312541,2.281286
min,0.000000,7.000000,0.000000,53.500000,0.000000,39.600000,81.800000,64.800000,41.300000,39.600000,56.600000,16.000000,59.600000,57.800000,0.000000,0.000000
25%,3.000000,16.000000,20.000000,76.900000,5.000000,60.700000,94.600000,86.500000,69.400000,71.675000,81.000000,47.900000,81.400000,82.100000,15.400000,1.000000
50%,4.000000,20.000000,36.400000,81.900000,7.000000,67.000000,96.400000,90.900000,76.650000,79.200000,85.600000,55.600000,86.300000,85.800000,21.400000,2.000000
75%,6.000000,24.000000,50.000000,86.000000,9.000000,72.625000,97.800000,93.900000,82.500000,85.125000,89.000000,63.800000,90.000000,88.900000,28.600000,4.000000
max,17.000000,43.000000,100.000000,94.300000,18.000000,87.000000,100.000000,100.000000,97.800000,96.500000,97.100000,90.800000,96.800000,95.400000,62.500000,14.000000

In [ ]:
# 열이 많아서 슬라이싱 - 3

df[['경합 지상', '경합 공중','태클', '클리어링', '인터셉트', '차단', '획득', '블락', '볼미스', '파울', '피파울', '경고', '퇴장',
       '기준', '시즌', '경기결과', '소속 선수 수', '평균 나이', '용병 수', '평균 가치', '총 가치']].describe()

,경합 지상,경합 공중,태클,클리어링,인터셉트,차단,획득,블락,볼미스,파울,피파울,경고,퇴장,시즌
count,1332.000000,1332.00000,1332.000000,1332.000000,1332.000000,1332.00000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000,1332.000000
mean,49.995420,50.00000,39.943393,27.536036,26.565315,25.37988,63.234234,14.014264,6.609610,11.750000,11.277027,1.748498,0.032282,2021.972973
std,10.477355,8.49709,18.117761,13.753690,9.359556,12.52459,18.389494,9.583307,2.786546,3.891055,3.774323,1.278836,0.181014,0.810815
min,0.000000,23.80000,0.000000,2.000000,3.000000,5.00000,25.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,2021.000000
25%,44.400000,44.20000,27.600000,17.000000,20.000000,16.00000,49.000000,4.000000,5.000000,9.000000,9.000000,1.000000,0.000000,2021.000000
50%,50.000000,50.00000,37.500000,26.000000,27.000000,21.00000,60.000000,15.000000,6.000000,11.000000,11.000000,2.000000,0.000000,2022.000000
75%,55.600000,55.80000,50.000000,37.000000,33.000000,34.00000,76.000000,21.000000,8.000000,14.000000,14.000000,3.000000,0.000000,2023.000000
max,100.000000,76.20000,100.000000,74.000000,64.000000,72.00000,125.000000,44.000000,17.000000,27.000000,25.000000,8.000000,2.000000,2023.000000