# Test Data 만들기

 - 2023년 K리그 1의 36Rnd, 37Rnd 데이터를 가져와 모델에 맞게 전처리

In [1]:
import pandas as pd
test_df = pd.read_excel('3637R.xlsx', engine='openpyxl')
test_df.head(3)
# display(test_df)
print(test_df.shape)

(24, 76)

In [2]:
# K_Columns 에서 컬럼명 가져오기
names = pd.read_excel('k_datasets\K_columns.xlsx', engine="openpyxl")
print(names.shape)
names.head()

(2, 48)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-39,LABEL-40,LABEL-41,LABEL-42,LABEL-43,LABEL-44,LABEL-45,LABEL-46,LABEL-47,LABEL-48
0,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,블락,볼미스,파울,피파울,경고,퇴장,NaN,NaN,NaN,NaN
1,시도,성공,성공%,시도,성공,성공%,시도,성공,성공%,시도,...,성공%,시도,성공,성공%,시도,성공,성공%,시도,성공,성공%

In [3]:
# 필요없는 열 제거 (성공%만 가져옴)
temp = names.drop(columns=['LABEL-45','LABEL-46','LABEL-47','LABEL-48']) 

# 컬럼명 가져와서 리스트로 저장
rows = temp.iloc[0].to_list()
print(len(rows))
print(rows)

44
['Rnd.', '대회', 'H/A', '득점', '도움', '슈팅', '유효 슈팅', '블락된슈팅', '벗어난슈팅', 'PA내 슈팅', 'PA외 슈팅', '프리킥 슈팅', '프리킥 유효슈팅', '프리킥 크로스', '오프사이드', '코너킥', '스로인', '드리블', '패스', '키패스', '전방패스', '후방패스', '횡패스', '공격진영 패스', '수비진영 패스', '중앙진영 패스', '롱패스', '중거리패스', '단거리패스', '크로스', '탈압박', '경합 지상', '경합 공중', '태클', '클리어링', '인터셉트', '차단', '획득', '블락', '볼미스', '파울', '피파울', '경고', '퇴장']

In [4]:
# df의 컬럼 개수를 K_columns에 맞춰 개수 맞추기
drop_columns = ['14', '15','20','21','23','24','27', '28' ,'30' ,'31' ,'33' ,'34', '36', '37', '39', '40','42', '43' ,'45',
               '46' ,'48', '49' ,'51' ,'52' ,'54', '55', '58', '59', '61', '62', '64', '65']
for idx in (drop_columns):
    # print(idx)
    test_df = test_df.drop(columns=[f'Unnamed: {int(idx)-1}'])

# 확인
print(test_df.shape)
# print(df.columns)
test_df.head(24)

(24, 44)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75
0,36,울산vs포항,HOME,3,2,11,3,1,7,9,...,26,36,21,45,17,3,8,8,2,0
1,37,인천vs울산,AWAY,1,0,16,4,4,8,13,...,17,42,29,68,15,9,5,9,1,0
2,36,수원FCvs수원,AWAY,3,2,13,6,4,3,4,...,58,22,23,52,15,9,6,9,2,1
3,37,서울vs수원,AWAY,1,0,15,5,4,6,11,...,45,46,25,73,23,8,9,12,2,0
4,36,울산vs포항,AWAY,2,1,14,6,3,5,9,...,23,37,19,55,18,6,9,7,2,0
5,37,포항vs대구,HOME,1,0,9,3,1,5,5,...,18,42,29,60,20,3,14,10,3,0
6,36,제주vs서울,HOME,0,0,12,5,2,5,11,...,23,46,10,46,22,5,12,7,1,0
7,37,제주vs대전,HOME,0,0,13,6,2,5,7,...,30,53,20,51,19,8,10,13,3,0
8,36,인천vs전북,AWAY,1,1,7,2,3,2,3,...,24,39,19,47,21,11,11,10,2,0
9,37,전북vs광주,HOME,2,1,10,5,0,5,6,...,35,39,20,40,27,8,11,10,1,0
10,36,제주vs서울,AWAY,0,0,13,2,3,8,7,...,20,35,25,57,27,4,8,12,2,0
11,37,서울vs수원,HOME,0,0,8,0,3,5,4,...,46,48,9,50,24,4,12,9,3,1
12,36,대전vs강원,HOME,0,0,4,0,1,3,0,...,34,48,22,81,30,3,15,9,1,0
13,37,제주vs대전,AWAY,2,1,11,3,2,6,6,...,37,48,24,66,12,6,14,10,2,0
14,36,대구vs광주,HOME,1,1,10,3,2,5,7,...,12,24,21,49,20,4,11,8,0,0
15,37,포항vs대구,AWAY,0,0,13,5,3,5,9,...,29,58,27,47,19,7,10,14,2,0
16,36,인천vs전북,HOME,1,0,13,3,5,5,6,...,34,43,12,56,17,8,11,11,3,0
17,37,인천vs울산,HOME,3,3,15,9,1,5,9,...,43,45,20,64,29,8,9,5,1,0
18,36,대전vs강원,AWAY,1,1,16,4,4,8,6,...,48,52,27,74,21,4,9,14,1,0
19,37,강원vs수원FC,HOME,2,1,8,2,3,3,8,...,45,51,21,52,28,5,17,5,3,0
20,36,대구vs광주,AWAY,1,1,10,2,4,4,3,...,27,27,20,49,28,14,8,11,2,0
21,37,전북vs광주,AWAY,0,0,10,2,4,4,5,...,22,42,13,57,14,4,13,11,2,0
22,36,수원FCvs수원,HOME,2,2,24,7,3,14,15,...,42,29,13,90,17,10,9,6,2,0
23,37,강원vs수원FC,AWAY,0,0,11,1,4,6,10,...,16,57,25,71,20,7,7,15,0,0

In [5]:
test_df.columns = rows
# test_test_df

In [6]:
test_df['기준'] = None

a = ['ulsan','ulsan','suwon','suwon', 'pohang','pohang', 'jeju', 'jeju', 'jeonbuk','jeonbuk',
     'seoul', 'seoul', 'daejeon','daejeon', 'daegu','daegu', 'incheon', 'incheon', 'gangwon', 'gangwon',
     'gwangju', 'gwangju', 'suwonFC', 'suwonFC']

test_df['기준'] = a
test_df['시즌'] = 2023

In [7]:
# 대회별 득점 비교 후 경기결과 열에 저장
for i in test_df["대회"].value_counts().index.tolist():
    for j in range(1,39): # 총 35개 라운드 수집
        H_score = test_df[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "HOME")]["득점"]
        A_score = test_df[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "AWAY")]["득점"]
        if len(H_score) > 0:
            if H_score.iloc[0] > A_score.iloc[0]:
                test_df.loc[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "HOME"), "경기결과"] = 'W'
                test_df.loc[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "AWAY"), "경기결과"] = 'L'
            elif H_score.iloc[0] < A_score.iloc[0]:
                test_df.loc[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "HOME"), "경기결과"] = 'L'
                test_df.loc[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "AWAY"), "경기결과"] = 'W'
            else:
                test_df.loc[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "HOME"), "경기결과"] = 'D'
                test_df.loc[(test_df["대회"] == i) & (test_df["Rnd."] == j) & (test_df["H/A"] == "AWAY"), "경기결과"] = 'D'

In [8]:
# 보기좋게 라운드 순으로 정렬
test_df = test_df.sort_values('Rnd.')

# 36 라운드 승패 확인
# test_df.head(12)

# 트랜스퍼마켓 데이터 전처리

In [9]:
tm_data_2023 = pd.read_excel('k_datasets/K_trsfmk_2023.xlsx', engine='openpyxl').drop(columns=['LABEL-1','LABEL-2','LABEL-4'])

# 열 이름 변경경
tm_data_2023 = tm_data_2023.rename(columns={'LABEL-3' : '구단', 'LABEL-5' : '소속 선수 수',
                                'LABEL-6' : '평균 나이','LABEL-7' : '용병 수',
                                'LABEL-8' : '평균 가치', 'LABEL-9' : '총 가치'})

# 구단 이름 수정
tm_data_2023['구단'] = ['jeonbuk', 'ulsan', 'seoul', 'suwon', 'daejeon', 'gangwon',
                           'jeju', 'incheon', 'gwangju', 'pohang','daegu','suwonFC']

# 단위 제거
tm_data_2023['평균 가치'] = tm_data_2023['평균 가치'].str.replace('€', '').str.replace('k', '').astype(float)
tm_data_2023['총 가치'] = tm_data_2023['총 가치'].str.replace('€', '').str.replace('m', '').astype(float)

In [10]:
# df에 tm_data_2023 합치기
tm_columns = tm_data_2023.columns[1:]

# df에 열 먼저 생성
for column in tm_columns:
    test_df[f'{column}'] = None
# test_df.head(1)


#2023
for column in tm_data_2023.columns[1:]:
    for i in test_df['기준']:
        for j in tm_data_2023['구단']:
            if i == j:
                test_df.loc[(test_df['기준'] == i) &(test_df['시즌'] == 2023), f'{column}'] = tm_data_2023.loc[tm_data_2023['구단'] == j , f'{column}'].values[0]
print('2023 end !')

test_df.head(1)

2023 end !

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,경고,퇴장,기준,시즌,경기결과,소속 선수 수,평균 나이,용병 수,평균 가치,총 가치
0,36,울산vs포항,HOME,3,2,11,3,1,7,9,...,2,0,ulsan,2023,W,30,28.8,5,632.0,18.95

In [11]:
import pandas as pd

# 'df'라는 이름으로 DataFrame이 있다고 가정합니다.
# '대회', '시즌', '라운드', 'H/A'를 기준으로 각 대회에 대한 두 행을 찾아 합칩니다.

new_rows = []

# '대회', '시즌', '라운드', 'H/A' 열을 기준으로 각 대회에 대한 행을 찾아 합칩니다.
unique_competitions = test_df['대회'].unique()

for competition in unique_competitions:
    competition_rows = test_df[test_df['대회'] == competition]
    
    # '시즌', '라운드', 'H/A' 열을 고려하여 대회에 대한 행을 찾아 합칩니다.
    unique_seasons = competition_rows['시즌'].unique()
    
    for season in unique_seasons:
        season_rows = competition_rows[competition_rows['시즌'] == season]
        
        unique_rounds = season_rows['Rnd.'].unique()
        
        for rnd in unique_rounds:
            round_rows = season_rows[season_rows['Rnd.'] == rnd]
            
            # 'H/A' 열을 기준으로 원정과 원정를 구분하여 대회, 시즌, 라운드에 대한 두 행을 합칩니다.
            home_row = round_rows[round_rows['H/A'] == 'HOME'].iloc[0]
            away_row = round_rows[round_rows['H/A'] == 'AWAY'].iloc[0]
            
            merged_row = pd.concat([home_row, away_row]).reset_index(drop=True)
            new_rows.append(merged_row)

# 새로운 DataFrame을 생성합니다.
new_test_df = pd.DataFrame(new_rows)

# 새로운 DataFrame을 출력합니다.
new_test_df

,0,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,103
0,36,울산vs포항,HOME,3,2,11,3,1,7,9,...,2,0,pohang,2023,L,37,25.6,4,281.0,10.40
1,36,수원FCvs수원,HOME,2,2,24,7,3,14,15,...,2,1,suwon,2023,W,47,26.0,7,314.0,14.78
2,36,대구vs광주,HOME,1,1,10,3,2,5,7,...,2,0,gwangju,2023,D,33,26.3,5,329.0,10.85
3,36,제주vs서울,HOME,0,0,12,5,2,5,11,...,2,0,seoul,2023,D,42,25.4,6,358.0,15.05
4,36,대전vs강원,HOME,0,0,4,0,1,3,0,...,1,0,gangwon,2023,W,45,24.6,6,274.0,12.33
5,36,인천vs전북,HOME,1,0,13,3,5,5,6,...,2,0,jeonbuk,2023,D,47,25.2,6,415.0,19.50
6,37,전북vs광주,HOME,2,1,10,5,0,5,6,...,2,0,gwangju,2023,L,33,26.3,5,329.0,10.85
7,37,강원vs수원FC,HOME,2,1,8,2,3,3,8,...,0,0,suwonFC,2023,L,37,27.1,4,277.0,10.25
8,37,인천vs울산,HOME,3,3,15,9,1,5,9,...,1,0,ulsan,2023,L,30,28.8,5,632.0,18.95
9,37,서울vs수원,HOME,0,0,8,0,3,5,4,...,2,0,suwon,2023,W,47,26.0,7,314.0,14.78
10,37,제주vs대전,HOME,0,0,13,6,2,5,7,...,2,0,daejeon,2023,W,45,24.5,5,285.0,12.83
11,37,포항vs대구,HOME,1,0,9,3,1,5,5,...,2,0,daegu,2023,L,41,24.2,5,254.0,10.40

In [12]:
merged_columns = ['Rnd.', '대회', 'H/A', '홈 득점', '홈 도움', '홈 슈팅', '홈 유효 슈팅', '홈 블락된슈팅', '홈 벗어난슈팅',
       '홈 PA내 슈팅', '홈 PA외 슈팅', '홈 프리킥 슈팅', '홈 프리킥 유효슈팅', '홈 프리킥 크로스', '홈 오프사이드', '홈 코너킥',
       '홈 스로인', '홈 드리블', '홈 패스', '홈 키패스', '홈 전방패스', '홈 후방패스', '홈 횡패스', '홈 공격진영 패스', '홈 수비진영 패스',
       '홈 중앙진영 패스', '홈 롱패스', '홈 중거리패스', '홈 단거리패스', '홈 크로스', '홈 탈압박', '홈 경합 지상', '홈 경합 공중',
       '홈 태클', '홈 클리어링', '홈 인터셉트', '홈 차단', '홈 획득', '홈 블락', '홈 볼미스', '홈 파울', '홈 피파울', '홈 경고', '홈 퇴장',
       '기준', '시즌', '홈 경기결과', '홈 소속 선수 수', '홈 평균 나이', '홈 용병 수', '홈 평균 가치', '홈 총 가치',
       
       'Rnd.2', '대회2', 'H/A2', '원정 득점', '원정 도움', '원정 슈팅', '원정 유효 슈팅', '원정 블락된슈팅', '원정 벗어난슈팅',
       '원정 PA내 슈팅', '원정 PA외 슈팅', '원정 프리킥 슈팅', '원정 프리킥 유효슈팅', '원정 프리킥 크로스', '원정 오프사이드', '원정 코너킥',
       '원정 스로인', '원정 드리블', '원정 패스', '원정 키패스', '원정 전방패스', '원정 후방패스', '원정 횡패스', '원정 공격진영 패스', '원정 수비진영 패스',
       '원정 중앙진영 패스', '원정 롱패스', '원정 중거리패스', '원정 단거리패스', '원정 크로스', '원정 탈압박', '원정 경합 지상', '원정 경합 공중',
       '원정 태클', '원정 클리어링', '원정 인터셉트', '원정 차단', '원정 획득', '원정 블락', '원정 볼미스', '원정 파울', '원정 피파울', '원정 경고', '원정 퇴장',
       '기준2', '시즌2', '원정 경기결과', '원정 소속 선수 수', '원정 평균 나이', '원정 용병 수', '원정 평균 가치', '원정 총 가치']

In [13]:
new_test_df.columns = merged_columns
new_test_df = new_test_df.drop(columns=['Rnd.2', '대회2', '시즌2', 'H/A', 'H/A2'])
new_test_df = new_test_df.rename(columns={'기준':'홈 팀', '기준2':'원정 팀'})
new_test_df

,Rnd.,대회,홈 득점,홈 도움,홈 슈팅,홈 유효 슈팅,홈 블락된슈팅,홈 벗어난슈팅,홈 PA내 슈팅,홈 PA외 슈팅,...,원정 피파울,원정 경고,원정 퇴장,원정 팀,원정 경기결과,원정 소속 선수 수,원정 평균 나이,원정 용병 수,원정 평균 가치,원정 총 가치
0,36,울산vs포항,3,2,11,3,1,7,9,2,...,7,2,0,pohang,L,37,25.6,4,281.0,10.40
1,36,수원FCvs수원,2,2,24,7,3,14,15,9,...,9,2,1,suwon,W,47,26.0,7,314.0,14.78
2,36,대구vs광주,1,1,10,3,2,5,7,3,...,11,2,0,gwangju,D,33,26.3,5,329.0,10.85
3,36,제주vs서울,0,0,12,5,2,5,11,1,...,12,2,0,seoul,D,42,25.4,6,358.0,15.05
4,36,대전vs강원,0,0,4,0,1,3,0,4,...,14,1,0,gangwon,W,45,24.6,6,274.0,12.33
5,36,인천vs전북,1,0,13,3,5,5,6,7,...,10,2,0,jeonbuk,D,47,25.2,6,415.0,19.50
6,37,전북vs광주,2,1,10,5,0,5,6,4,...,11,2,0,gwangju,L,33,26.3,5,329.0,10.85
7,37,강원vs수원FC,2,1,8,2,3,3,8,0,...,15,0,0,suwonFC,L,37,27.1,4,277.0,10.25
8,37,인천vs울산,3,3,15,9,1,5,9,6,...,9,1,0,ulsan,L,30,28.8,5,632.0,18.95
9,37,서울vs수원,0,0,8,0,3,5,4,4,...,12,2,0,suwon,W,47,26.0,7,314.0,14.78
10,37,제주vs대전,0,0,13,6,2,5,7,6,...,10,2,0,daejeon,W,45,24.5,5,285.0,12.83
11,37,포항vs대구,1,0,9,3,1,5,5,4,...,14,2,0,daegu,L,41,24.2,5,254.0,10.40

In [14]:
# 나중에도 불러 올 수 있도록 저장
new_test_df.to_csv('K-League-Test3536.csv')