In [1]:
from glob import glob

import pandas as pd


datas = glob('k_datasets/*.xlsx')
print(datas)

teams = [xlsx.split('_')[-2] for xlsx in datas[:12]]

# concat 기준이 될 df  먼저 생성, 
df = pd.read_excel(f'{datas[0]}', engine='openpyxl')

# H/A 헷갈려서 기준 잡는 열 생성
df['기준'] = teams[0]

# 새로운 df 불러오고 기준 df에 concat하기
for xlsx in datas[1:12]:
    team_name = xlsx.split('_')[-2]
    df_temp = pd.read_excel(f'{xlsx}', engine="openpyxl")
    df_temp["기준"] = f'{team_name}'
    df = pd.concat([df, df_temp])
print(df.shape)
df.tail()

['k_datasets\\2023_daegu_data.xlsx', 'k_datasets\\2023_daejeon_data.xlsx', 'k_datasets\\2023_gangwon_data.xlsx', 'k_datasets\\2023_gwangju_data.xlsx', 'k_datasets\\2023_incheon_data.xlsx', 'k_datasets\\2023_jeju_data.xlsx', 'k_datasets\\2023_jeonbuk_data.xlsx', 'k_datasets\\2023_pohang_data.xlsx', 'k_datasets\\2023_seoul_data.xlsx', 'k_datasets\\2023_suwonFC_data.xlsx', 'k_datasets\\2023_suwon_data.xlsx', 'k_datasets\\2023_ulsan_data.xlsx', 'k_datasets\\K_columns.xlsx', 'k_datasets\\K_trsfmk.xlsx']
(420, 77)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-68,LABEL-69,LABEL-70,LABEL-71,LABEL-72,LABEL-73,LABEL-74,LABEL-75,LABEL-76,기준
30,31,수원FCvs울산,AWAY,3,3,9,8,0,1,6,...,40,20,47,17,11,10,9,1,0,ulsan
31,32,포항vs울산,AWAY,0,0,4,1,0,3,2,...,31,29,52,20,5,11,11,5,0,ulsan
32,33,울산vs인천,HOME,0,0,9,2,1,6,5,...,43,12,42,16,7,7,2,2,0,ulsan
33,34,광주vs울산,AWAY,0,0,17,5,6,6,6,...,38,18,58,11,11,16,6,1,0,ulsan
34,35,울산vs대구,HOME,2,2,12,5,2,5,5,...,34,24,59,11,7,8,7,1,0,ulsan

In [2]:
# K_Columns 에서 컬럼명 가져오기
names = pd.read_excel(f'{datas[-2]}', engine="openpyxl")
print(names.shape)
names.head()

(2, 48)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-39,LABEL-40,LABEL-41,LABEL-42,LABEL-43,LABEL-44,LABEL-45,LABEL-46,LABEL-47,LABEL-48
0,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,블락,볼미스,파울,피파울,경고,퇴장,NaN,NaN,NaN,NaN
1,시도,성공,성공%,시도,성공,성공%,시도,성공,성공%,시도,...,성공%,시도,성공,성공%,시도,성공,성공%,시도,성공,성공%

In [3]:
# 필요없는 열 제거 (성공%만 가져옴)
temp = names.drop(columns=['LABEL-45','LABEL-46','LABEL-47','LABEL-48']) 

# 컬럼명 가져와서 리스트로 저장
rows = temp.iloc[0].to_list()
print(len(rows))
print(rows)

44
['Rnd.', '대회', 'H/A', '득점', '도움', '슈팅', '유효 슈팅', '블락된슈팅', '벗어난슈팅', 'PA내 슈팅', 'PA외 슈팅', '프리킥 슈팅', '프리킥 유효슈팅', '프리킥 크로스', '오프사이드', '코너킥', '스로인', '드리블', '패스', '키패스', '전방패스', '후방패스', '횡패스', '공격진영 패스', '수비진영 패스', '중앙진영 패스', '롱패스', '중거리패스', '단거리패스', '크로스', '탈압박', '경합 지상', '경합 공중', '태클', '클리어링', '인터셉트', '차단', '획득', '블락', '볼미스', '파울', '피파울', '경고', '퇴장']

In [4]:
# df의 컬럼 개수를 K_columns에 맞춰 개수 맞추기
drop_columns = ['14', '15','20','21','23','24','27', '28' ,'30' ,'31' ,'33' ,'34', '36', '37', '39', '40','42', '43' ,'45',
               '46' ,'48', '49' ,'51' ,'52' ,'54', '55', '58', '59', '61', '62', '64', '65']
for idx in (drop_columns):
    df = df.drop(columns=[f'LABEL-{idx}'])

# 확인
print(df.shape)
# print(df.columns)
df.head()

(420, 45)

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-68,LABEL-69,LABEL-70,LABEL-71,LABEL-72,LABEL-73,LABEL-74,LABEL-75,LABEL-76,기준
0,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,28,17,51,19,4,16,9,3,0,daegu
1,2,대구vs제주,HOME,1,0,13,3,2,8,6,...,18,25,61,20,4,19,13,2,0,daegu
2,3,강원vs대구,AWAY,1,1,14,6,1,7,8,...,30,19,76,20,13,14,13,1,0,daegu
3,4,대구vs전북,HOME,2,1,12,7,2,3,9,...,19,19,46,21,4,15,10,5,0,daegu
4,5,인천vs대구,AWAY,0,0,6,3,2,1,1,...,25,24,58,17,7,12,9,1,0,daegu

In [5]:
# 컬럼명 변경 ("기준"열 제외한)
for idx, column in enumerate(df.columns[:-1]):
    df = df.rename(columns={f"{column}": f"{rows[idx]}"})

# 컬럼명 변경 확인
df.head(1)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,인터셉트,차단,획득,블락,볼미스,파울,피파울,경고,퇴장,기준
0,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,28,17,51,19,4,16,9,3,0,daegu

In [6]:
# 대회별 득점 비교 후 경기결과 열에 저장
for i in df["대회"].value_counts().index.tolist():
    for j in range(36): # 총 35개 라운드 수집
        H_score = df[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME")]["득점"]
        A_score = df[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY")]["득점"]
        if len(H_score) > 0:
            if H_score.iloc[0] > A_score.iloc[0]:
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'W'
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY"), "경기결과"] = 'L'
            elif H_score.iloc[0] < A_score.iloc[0]:
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'L'
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY"), "경기결과"] = 'W'
            else:
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'D'
                df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "AWAY"), "경기결과"] = 'D'

C:\Users\HongWonJin\AppData\Local\Temp\ipykernel_21548\1168619852.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'W' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df["대회"] == i) & (df["Rnd."] == j) & (df["H/A"] == "HOME"), "경기결과"] = 'W'

In [7]:
# 보기좋게 라운드 순으로 정렬
df = df.sort_values('Rnd.')

# 1,2라운드 승패 확인
df.head(24)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,차단,획득,블락,볼미스,파울,피파울,경고,퇴장,기준,경기결과
0,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,17,51,19,4,16,9,3,0,daegu,L
0,1,수원vs광주,HOME,0,0,10,5,4,1,7,...,21,67,16,3,13,12,2,0,suwon,L
0,1,대전vs강원,HOME,2,1,9,4,1,4,5,...,22,71,20,8,13,7,5,0,daejeon,W
0,1,제주vs수원FC,HOME,0,0,14,6,2,6,12,...,21,71,12,8,15,11,3,0,jeju,D
0,1,울산vs전북,HOME,2,0,10,4,4,2,7,...,22,63,17,5,11,16,2,0,ulsan,W
0,1,울산vs전북,AWAY,1,1,14,5,5,4,9,...,15,73,20,12,17,11,2,0,jeonbuk,L
0,1,대전vs강원,AWAY,0,0,8,1,1,6,6,...,25,67,17,4,7,13,1,0,gangwon,L
0,1,서울vs인천,HOME,2,1,13,7,2,4,7,...,16,41,31,5,16,12,3,0,seoul,W
0,1,포항vs대구,HOME,3,3,12,5,2,5,7,...,18,52,19,6,9,14,1,0,pohang,W
0,1,제주vs수원FC,AWAY,0,0,9,2,2,5,7,...,14,55,19,7,11,15,3,0,suwonFC,D
0,1,서울vs인천,AWAY,1,0,17,5,4,8,13,...,11,83,16,6,12,16,2,0,incheon,L
0,1,수원vs광주,AWAY,1,1,12,3,3,6,7,...,32,73,33,8,12,13,2,0,gwangju,W
1,2,수원FCvs포항,HOME,1,1,6,1,2,3,5,...,29,74,25,8,14,10,1,1,suwonFC,L
1,2,인천vs대전,HOME,3,1,24,12,4,8,20,...,15,83,33,6,10,9,3,1,incheon,D
1,2,대구vs제주,AWAY,1,1,12,4,3,5,6,...,27,67,15,8,14,16,3,0,jeju,D
1,2,전북vs수원,HOME,1,0,10,4,1,5,6,...,19,66,21,7,16,10,2,0,jeonbuk,D
1,2,강원vs울산,AWAY,1,0,9,3,1,5,7,...,13,56,25,5,8,8,4,0,ulsan,W
1,2,광주vs서울,HOME,0,0,8,2,2,4,4,...,19,63,17,4,12,15,2,0,gwangju,L
1,2,인천vs대전,AWAY,3,3,9,5,3,1,6,...,20,63,19,8,11,10,2,0,daejeon,D
1,2,강원vs울산,HOME,0,0,12,1,4,7,6,...,18,71,16,3,8,8,0,0,gangwon,L
1,2,전북vs수원,AWAY,1,1,23,7,9,7,11,...,19,77,17,6,10,16,1,0,suwon,D
1,2,대구vs제주,HOME,1,0,13,3,2,8,6,...,25,61,20,4,19,13,2,0,daegu,D
1,2,광주vs서울,AWAY,2,2,8,3,1,4,5,...,31,55,25,7,15,12,2,0,seoul,W
1,2,수원FCvs포항,AWAY,2,1,11,5,1,5,8,...,26,81,28,7,10,14,1,0,pohang,W

In [8]:
# 마지막 라운드 승패 확인
df.tail(12)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,차단,획득,블락,볼미스,파울,피파울,경고,퇴장,기준,경기결과
34,35,강원vs제주,AWAY,1,0,8,2,2,4,7,...,26,59,15,8,4,15,3,0,jeju,D
34,35,수원FCvs서울,HOME,3,2,14,8,2,4,8,...,21,47,15,3,9,9,0,0,suwonFC,L
34,35,수원FCvs서울,AWAY,4,0,17,9,1,7,12,...,24,59,16,9,9,9,1,0,seoul,W
34,35,전북vs포항,AWAY,1,0,12,7,1,4,6,...,20,46,25,5,9,15,0,0,pohang,D
34,35,전북vs포항,HOME,1,0,13,5,3,5,8,...,19,57,19,2,16,8,3,0,jeonbuk,D
34,35,광주vs인천,AWAY,2,0,7,2,2,3,3,...,25,29,19,12,9,7,3,0,incheon,W
34,35,광주vs인천,HOME,0,0,14,3,3,8,7,...,10,63,15,6,7,9,1,0,gwangju,L
34,35,강원vs제주,HOME,1,1,11,4,2,5,6,...,25,69,18,5,16,4,4,0,gangwon,D
34,35,수원vs대전,AWAY,2,2,9,3,2,4,5,...,11,51,20,4,9,7,1,0,daejeon,D
34,35,울산vs대구,AWAY,0,0,6,4,0,2,4,...,16,52,27,6,7,8,2,0,daegu,L
34,35,수원vs대전,HOME,2,1,9,4,1,4,8,...,23,49,20,8,8,9,1,0,suwon,D
34,35,울산vs대구,HOME,2,2,12,5,2,5,5,...,24,59,11,7,8,7,1,0,ulsan,W

In [9]:
# transfer markt 데이터 불러오기
tm_data_2023 = pd.read_excel(f'{datas[-1]}', engine='openpyxl')

# 필요없는 열 제거
tm_data_2023 = tm_data_2023.drop(columns=['LABEL-1','LABEL-2','LABEL-4'])

# 열 이름 변경
tm_data_2023 = tm_data_2023.rename(columns={'LABEL-3' : '구단', 'LABEL-5' : '소속 선수 수',
                                'LABEL-6' : '평균 나이','LABEL-7' : '용병 수',
                                'LABEL-8' : '평균 가치', 'LABEL-9' : '총 가치'})

# 구단 이름 수정
tm_data_2023['구단'] = ['jeonbuk', 'ulsan', 'seoul', 'suwon', 'daejeon', 'gangwon',
                           'jeju', 'incheon', 'gwangju', 'pohang','daegu','suwonFC']
tm_data_2023

         구단  소속 선수 수  평균 나이  용병 수  평균 가치     총 가치
0   jeonbuk       47   25.2     6  €415k  €19.50m
1     ulsan       30   28.8     5  €632k  €18.95m
2     seoul       42   25.4     6  €358k  €15.05m
3     suwon       47   26.0     7  €314k  €14.78m
4   daejeon       45   24.5     5  €285k  €12.83m
5   gangwon       45   24.6     6  €274k  €12.33m
6      jeju       31   27.5     3  €384k  €11.90m
7   incheon       35   26.3     5  €315k  €11.03m
8   gwangju       33   26.3     5  €329k  €10.85m
9    pohang       37   25.6     4  €281k  €10.40m
10    daegu       41   24.2     5  €254k  €10.40m
11  suwonFC       37   27.1     4  €277k  €10.25m

In [10]:
# df에 tm_data_2023 합치기
tm_columns = tm_data_2023.columns[1:]

# df에 열 먼저 생성
for column in tm_columns:
    df[f'{column}'] = None
df.head(1)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,피파울,경고,퇴장,기준,경기결과,소속 선수 수,평균 나이,용병 수,평균 가치,총 가치
0,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,9,3,0,daegu,L,None,None,None,None,None

In [19]:
tm_data_2023.columns[1:]

Index(['소속 선수 수', '평균 나이', '용병 수', '평균 가치', '총 가치'], dtype='object')

In [22]:
for column in tm_data_2023.columns[1:]:
    for i in df['기준']:
        for j in tm_data_2023['구단']:
            if i == j:
                df.loc[df['기준'] == i, f'{column}'] = tm_data_2023.loc[tm_data_2023['구단'] == j, f'{column}'].values[0]
df.head(24)

,Rnd.,대회,H/A,득점,도움,슈팅,유효 슈팅,블락된슈팅,벗어난슈팅,PA내 슈팅,...,피파울,경고,퇴장,기준,경기결과,소속 선수 수,평균 나이,용병 수,평균 가치,총 가치
0,1,포항vs대구,AWAY,2,1,9,4,3,2,6,...,9,3,0,daegu,L,41,24.2,5,€254k,€10.40m
0,1,수원vs광주,HOME,0,0,10,5,4,1,7,...,12,2,0,suwon,L,47,26.0,7,€314k,€14.78m
0,1,대전vs강원,HOME,2,1,9,4,1,4,5,...,7,5,0,daejeon,W,45,24.5,5,€285k,€12.83m
0,1,제주vs수원FC,HOME,0,0,14,6,2,6,12,...,11,3,0,jeju,D,31,27.5,3,€384k,€11.90m
0,1,울산vs전북,HOME,2,0,10,4,4,2,7,...,16,2,0,ulsan,W,30,28.8,5,€632k,€18.95m
0,1,울산vs전북,AWAY,1,1,14,5,5,4,9,...,11,2,0,jeonbuk,L,47,25.2,6,€415k,€19.50m
0,1,대전vs강원,AWAY,0,0,8,1,1,6,6,...,13,1,0,gangwon,L,45,24.6,6,€274k,€12.33m
0,1,서울vs인천,HOME,2,1,13,7,2,4,7,...,12,3,0,seoul,W,42,25.4,6,€358k,€15.05m
0,1,포항vs대구,HOME,3,3,12,5,2,5,7,...,14,1,0,pohang,W,37,25.6,4,€281k,€10.40m
0,1,제주vs수원FC,AWAY,0,0,9,2,2,5,7,...,15,3,0,suwonFC,D,37,27.1,4,€277k,€10.25m
0,1,서울vs인천,AWAY,1,0,17,5,4,8,13,...,16,2,0,incheon,L,35,26.3,5,€315k,€11.03m
0,1,수원vs광주,AWAY,1,1,12,3,3,6,7,...,13,2,0,gwangju,W,33,26.3,5,€329k,€10.85m
1,2,수원FCvs포항,HOME,1,1,6,1,2,3,5,...,10,1,1,suwonFC,L,37,27.1,4,€277k,€10.25m
1,2,인천vs대전,HOME,3,1,24,12,4,8,20,...,9,3,1,incheon,D,35,26.3,5,€315k,€11.03m
1,2,대구vs제주,AWAY,1,1,12,4,3,5,6,...,16,3,0,jeju,D,31,27.5,3,€384k,€11.90m
1,2,전북vs수원,HOME,1,0,10,4,1,5,6,...,10,2,0,jeonbuk,D,47,25.2,6,€415k,€19.50m
1,2,강원vs울산,AWAY,1,0,9,3,1,5,7,...,8,4,0,ulsan,W,30,28.8,5,€632k,€18.95m
1,2,광주vs서울,HOME,0,0,8,2,2,4,4,...,15,2,0,gwangju,L,33,26.3,5,€329k,€10.85m
1,2,인천vs대전,AWAY,3,3,9,5,3,1,6,...,10,2,0,daejeon,D,45,24.5,5,€285k,€12.83m
1,2,강원vs울산,HOME,0,0,12,1,4,7,6,...,8,0,0,gangwon,L,45,24.6,6,€274k,€12.33m
1,2,전북vs수원,AWAY,1,1,23,7,9,7,11,...,16,1,0,suwon,D,47,26.0,7,€314k,€14.78m
1,2,대구vs제주,HOME,1,0,13,3,2,8,6,...,13,2,0,daegu,D,41,24.2,5,€254k,€10.40m
1,2,광주vs서울,AWAY,2,2,8,3,1,4,5,...,12,2,0,seoul,W,42,25.4,6,€358k,€15.05m
1,2,수원FCvs포항,AWAY,2,1,11,5,1,5,8,...,14,1,0,pohang,W,37,25.6,4,€281k,€10.40m